### ISSUE TITLE
error in building the container

### ISSUE THREAD

**Issue by GINNOV** [sebastianbergmann/docker-execute-amiga#3]
Thank you for doing this!!

I tried out what you shared but I ran into this issue. Any clue on what to do to make it work?

/usr/local/bin/docker-execute-amiga AmiDwnUnder.bin 
Unable to find image 'jamesnetherton/fs-uae:latest' locally
latest: Pulling from jamesnetherton/fs-uae
f2b6b4884fc8: Pulling fs layer
95626f4633bf: Pulling fs layer
f2b6b4884fc8: Verifying Checksum
f2b6b4884fc8: Download complete
f2b6b4884fc8: Pull complete
95626f4633bf: Verifying Checksum
95626f4633bf: Download complete
95626f4633bf: Pull complete
Digest: sha256:a7c68279a7b3d17468900f73d83503e03865a9eb9fcbed5f90793fa040067102
Status: Downloaded newer image for jamesnetherton/fs-uae:latest
docker: Error response from daemon: Mounts denied: 
The path /var/folders/dj/8bhglv2n2zv5smdr9090jhbc0000gn/T/tmp.3K5gKhB0
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0038] error waiting for container: context canceled

**Comment by sebastianbergmann** [comment]
Looks like an issue specific to Docker on macOS. I cannot help with that, sorry.
